logging:
  level:
    ROOT: info
    org.hibernate.SQL: DEBUG
    com.drumond.spotify: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${database_name}://${postgres_url}:${postgres_port}/${postgres_db}
    username: ${postgres_username}
    password: ${postgres_password}
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: spotify
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: spotify
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: https://spotify.jp.auth0.com/
    client-id: ${auth0_client_id}
    client-secret: ${auth0_client_secret}